### ISSUE TITLE
Prevent the browser from freezing when evaluating long-running form

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-web#13] opened 2019-05-23 00:12 UTC
If you evaluate

```clojure
(simple-benchmark [x 1]
 (str 1)
 1e8)
```

The UI will appear to lock up. This appearance can be avoided by updating the output pane before commencing with evaluation.

(See https://github.com/replete-repl/replete-macos/issues/56)

**Comment by raymcdermott** [comment] 2019-05-24 07:51
I tried the evaluation using the macOS version of replete and had the same UX so not sure what the difference is.

**Comment by mfikes** [comment] 2019-05-24 11:11
@raymcdermott The macOS version of Replete with the fix hasn't been released yet... maybe you were trying that one?

**Comment by raymcdermott** [comment] 2019-05-24 11:53
very likely in that case :)

**Comment by raymcdermott** [comment] 2019-06-10 23:11
I cannot reproduce this with Chrome / Chromium (on macOS)

With Firefox (also only tested on macOS) you may see a warning for a long running JS process but never any ball spinning.

It seems like it's a Safari / JSC problem (confirming the discussion in the other issue).

I have made several attempts to update the output via re-frame and directly on the codemirror but not managed to make any differences yet. 

Further investigation required.

**Comment by mfikes** [comment] 2019-06-11 00:19
Yeah, I was testing on Safari.

**Comment by raymcdermott** [comment] 2019-06-11 10:17
I can't find any one liner tricks so far - please feel free to chip in with ideas :)

The JS people want you to use `async/await` or re-write the code with `setTimeout` and `setInterval` but I don't think these options are open to us if we want to provide generic support for all CLJS loop operations.

The big gun option is to run the eval in a web worker cos JS single thread. Web workers seem to be well supported now on the browsers so it looks like a viable and generic solution.

https://stackoverflow.com/questions/10344498/best-way-to-iterate-over-an-array-without-blocking-the-ui/10344560#10344560

I have never used a web worker before so should be interesting.

**Comment by raymcdermott** [comment] 2019-06-14 10:54
fixed by #30

**Closed as completed by raymcdermott** 2019-06-14 10:54 UTC
Labels: help wanted
