### ISSUE TITLE
Error requiring spec

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-web#14] opened 2019-05-23 00:21 UTC
```clojure
(require '[clojure.spec.alpha :as s])
```

yields

```
Execution error (Error) at (<cljs repl>:1).
re-seq must match against a string.
```

Then `(pst)` can be used to give some context. Here is the first portion

```
(pst)
re-seq must match against a string.
cljs$core$re_seq@http://localhost:9600/js/compiled/out/cljs/core.js:32966:21
replete$priv_repl$closure_index@http://localhost:9600/js/compiled/out/replete/priv_repl.js:399:25
cljs$core$IFn$_invoke$arity$2@http://localhost:9600/js/compiled/out/cljs/core.js:13177:14
cljs$core$IFn$_invoke$arity$2@http://localhost:9600/js/compiled/out/cljs/core.js:13462:63
G__12938__delegate@http://localhost:9600/js/compiled/out/cljs/core.js:35221:56
G__12938@http://localhost:9600/js/compiled/out/cljs/core.js:35236:31
replete$priv_repl$do_load_goog@http://localhost:9600/js/compiled/out/replete/priv_repl.js:627:90
replete$priv_repl$load@http://localhost:9600/js/compiled/out/replete/priv_repl.js:651:43
```

**Comment by raymcdermott** [comment] 2019-05-24 07:33
This was an accidental reversion caused by the prepl using the incorrect `load`. 

After PR #25 is merged I'll update the dep to actually fix.

**Closed as completed** 2019-05-24 11:48 UTC
